### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by palitu** [hooram/ownphotos#33]
This looks like a pretty cool project.

is there any plans to continue the work on this?

**Comment by petrk94** [comment]
+1

**Comment by palitu** [comment]
It looks nice, and has some cool features, I am currently using [Photato](https://github.com/trebonius0/Photato).  It is java, and requires no other DB's or anything, watches the filesystem and has a nice interface for tags, location and people.  But it also seems under-developed.

I have it with ~22k photos, on a NAS. so it takes Ages to Index them all. But i do like it.

**Comment by HesselTjeerdsma** [comment]
+1 also like this project!

**Comment by migueltg** [comment]
+1, it's a great project, we need more collaborators in order to help to @hooram

**Comment by guysoft** [comment]
I am willing to help, I have a fork that can docker build runs and can display images. Also sent an email to @hooram and hope to get an answer.

To deploy follow:
https://github.com/hooram/ownphotos-frontend/issues/8#issuecomment-447003146

**Comment by guysoft** [comment]
Ok, @hooram is here but a little quiet, so the answer is yes, at least on the devops side. 
Suggest @hooram says "yes" and closes this.

**Comment by PrplHaz4** [comment]
@hooram any chance we can get @guysoft added as a maintainer on this repo?  it seems like there's been a renewed interest in the project, and there's a bit of a backlog of easy "stuff" that can be merged in....

**Comment by guysoft** [comment]
Would gladly help out.
@hooram You can set this under project collaborators:
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by hooram** [comment]
@guysofy just sent an invitation.

**Comment by guysoft** [comment]
Accepted, thanks! Will merge my latest stuff too later today!

I am also trying to set up here an easy way to test stuff out in the
backend.

**Comment by guysoft** [comment]
Ok, merged, I am working on getting this project usable. So closing this issue, and please open new ones so we can fix stuff!
